service: server-images-by-category
frameworkVersion: "2"
useDotenv: true
configValidationMode: error
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  timeout: 15
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags:
      Name: "${env:TAG_NAME_BASE}-${env:ENVIRONMENT}-${self:custom.stage}-${env:REGION}"
      Environment: ${env:ENVIRONMENT}
      # Group: ${env:TAG_GROUP}
      # CostCenter: ${env:TAG_COST_CENTER}
      # Product: ${env:TAG_PRODUCT}
      POC: ${env:TAG_POC}
  tags:
    Name: "ranger-covid-service-${env:ENVIRONMENT}-${self:custom.stage}-${env:REGION}"
    Environment: ${env:ENVIRONMENT}
    # Group: ${env:TAG_GROUP}
    # CostCenter: ${env:TAG_COST_CENTER}
    # Product: ${env:TAG_PRODUCT}
    POC: ${env:TAG_POC}
  environment:
    STAGE: ${self:custom.stage}
    DEBUG: ${env:DEBUG, "false"}
    JWT_SECRET: ${env:JWT_SECRET}
    EXTENSION_API_TOKEN: ${env:EXTENSION_API_TOKEN}
    TABLE_NAME: ${env:TABLE_NAME}
    REGION: ${env:REGION}
  lambdaHashingVersion: 20201221
  httpApi:
    useProviderTags: true
    cors:
      allowedOrigins:
        - https://experience-dev-devinternal.elluciancloud.com
        - https://experience-test-internal.elluciancloud.com
        - https://experience-test.elluciancloud.com
        - https://experience.elluciancloud.com
      allowedMethods:
        - GET
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ imageTable, Arn ]
        # - arn:aws:dynamodb:us-east-1:035529058316:table/${env:TABLE_NAME}
# When deploying to AWS, using the following to restrict CORS to be allowed only for Ellucian Experience
#    cors:
#      allowedOrigins:
# The internal instances are for Ellucian employee, use. Not needed for Ellucian customers.
#        - https://experience-dev-devinternal.elluciancloud.com
#        - https://experience-test-internal.elluciancloud.com
#        - https://experience-test.elluciancloud.com
#        - https://experience.elluciancloud.com
#      allowedMethods:
#        - GET
custom:
  stage: ${opt:stage, env:STAGE}
plugins:
  - serverless-deployment-bucket
  - serverless-offline
  - serverless-provisioned-concurrency-autoscaling
  - serverless-bundle
functions:
  auth-handler:
    handler: src/authorizer.handler
    description: "This verifies a jwt with a shared_secret"
  gallery:
    handler: src/gallery.handler
    provisionedConcurrency: 1
    concurrencyAutoscaling: true
    events:
      - http:
          path: /api/gallery/{category}
          method: get
          cors:
            origins:
              - http://localhost:8081
              - https://*.elluciancloud.com
              - https://*.elluciancloud.com.au
              - https://*.elluciancloud.ie
              - https://*.elluciancloud.ca
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
  gallery-dynamo:
    handler: src/gallery-dynamo.handler
    provisionedConcurrency: 1
    concurrencyAutoscaling: true
    events:
      - http:
          path: /api/gallery-dynamo/{category}
          method: get
          cors:
            origins:
              - http://localhost:8081
              - https://*.elluciancloud.com
              - https://*.elluciancloud.com.au
              - https://*.elluciancloud.ie
              - https://*.elluciancloud.ca
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          path: /api/gallery-dynamo/
          method: post
          cors:
            origins:
              - http://localhost:8081
              - https://*.elluciancloud.com
              - https://*.elluciancloud.com.au
              - https://*.elluciancloud.ie
              - https://*.elluciancloud.ca
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
          authorizer:
            name: "auth-handler"
            identitySource: "method.request.header.Authorization"
            resultTtlInSeconds: 0


# this section runs/provisions for every deploy so beware
resources: # CloudFormation template syntax from here on.
  Resources:
    imageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: album
            AttributeType: S
          - AttributeName: imageUrl
            AttributeType: S
        KeySchema:
          - AttributeName: album
            KeyType: HASH
          - AttributeName: imageUrl
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
